#run with  python /home/atoshev/code/lagrangebench/main.py config=./validate_code/tgv2d/gns.yaml
extends: LAGRANGEBENCH_DEFAULTS

dataset:
  src: /home/tkalinov/code/sph_les_directory/sph_les/data/2D_TGV_DEBUG
  name: tgv2d

model:
  name: gns
  num_mp_steps: 10
  latent_dim: 64
  num_mlp_layers: 2
  particle_type_embedding_size: 16

train:
  optimizer:
    lr_start: 1.0e-4
    lr_final: 1.0e-6
    lr_decay_rate: 0.1
    lr_decay_steps: 100000
  pushforward:
    steps: [-1]
    unrolls: [0]
    probs: [1]

  batch_size: 1

  step_max: 10000

  num_workers: 0

  noise_std: 0 #3.0e-4

eval:
  n_rollout_steps: 5

  rollout_dir: "rollouts"

  train:
    n_trajs: 1
    metrics_stride: 1

  infer:
    n_trajs: 1
    batch_size: 1
    metrics: ["mse", "e_kin"]
    out_type: "vtk"

neighbors:
  multiplier: 2.0

logging:
  log_steps: 1
  eval_steps: 10
  wandb: True
  wandb_project: tgv2d_val_lagBench
  run_name: gns_tgv2d_LB
