# configs/model/gns.yaml

# Specify the correct path to the SimulatorLitModule in the Lightning module
_target_: src.models.gino_module.GINOLitModule # Adjust this to the actual path for your GNS Lightning module

net:
  # Specify the correct path to the GNS model implementation (GINOSimulator) within the SimulatorLitModule
  _target_: src.models.gino_module.GINOSimulator # Adjust this to the actual path for your GNS simulator model
  _partial_: true
  model_name: "gino" # gino, interp_fno
  isotropic_norm: false
  noise_std: 3.0e-4
  dataset_path: ${data.data_dir}
  return_x_grid: false
  ### GINO kwargs
  in_gno_transform_type: linear
  out_gno_transform_type: linear
  gno_pos_embed_type: transformer # "transformer", "nerf"
  fno_in_channels: ${vars.dim}
  fno_n_modes: [32, 32]
  fno_hidden_channels: 32
  fno_norm: instance_norm
  # projection_channel_ratio: 4
  fno_n_layers: 4
  fno_implementation: "reconstructed" # "reconstructed", "factorized"
  fno_skip: "linear" # "linear", "soft-gating"
  query_resolution: [64, 64]
  # next arguments are for interp_fno
  nbrs_condition: knn
  nbrs_k: 3
  nbrs_cutoff_factor: 3.0 # for quintic kernel, we use 3*average_particle_distance
  nbrs_kernel: "xsqinv" # "quintic", "xsqinv"

# Optimizer configuration
optimizer:
  _partial_: true
  _target_: torch.optim.AdamW # SGD with lr=0.03 does pretty well on overfitting
  lr: 1.0e-4
  weight_decay: 1.e-4

# # Scheduler configuration
# scheduler:
#   _partial_: true
#   _target_: src.utils.schedulers.LinearWarmupCosineAnnealingLR
#   optimizer: ${..optimizer} # Reference optimizer from the model configuration
#   min_lr: 0.0001
#   steps_per_epoch: 1
#   warmup_epochs: 0
#   max_epochs: 10

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 100_000
  gamma: 0.5

# Set whether to compile the model
compile: true

# Adjust based on the available hardware
accelerator: ${trainer.accelerator}

neuralsph:
  val:
    is_tvf: False
    dt_factor: 1
    num_steps: 0
  test:
    is_tvf: False
    dt_factor: 1
    num_steps: 0

num_rollout_steps: ${vars.num_rollout_steps}
active_metrics: ["mse", "e_kin", "mse_pos"]
metric_space:
  val: "norm" # {"phys", "norm", "diff"} = physical, normalized, difference
  test: "phys"
  interpolate:
    condition: radius # "radius", "knn"
    k: 15
    cutoff_factor: 2.0 # for Quintic would have been 3, but here it is just a metric
    kernel: "quintic" # "quintic", "xsqinv"

visualize:
  vis_test:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: "${paths.log_dir}/train/runs/WANDB_ID/rlt/test" #interpolation of the ID is done in the main script
  vis_val:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: null
