# configs/model/gns.yaml

# Specify the correct path to the SimulatorLitModule in the Lightning module
_target_: src.models.gnn_module.GNNLitModule # Adjust this to the actual path for your GNS Lightning module

net:
  # Specify the correct path to the GNS model implementation (GNNSimulator) within the SimulatorLitModule
  _target_: src.models.gnn_module.GNNSimulator # Adjust this to the actual path for your GNS simulator model
  _partial_: true
  model_name: "gns"
  input_seq_length: ${vars.input_seq_length}
  latent_dim: 128
  num_message_passing_steps: 10
  noise_std: 0.0
  num_particle_types: 9
  particle_type_embedding_size: 16
  dataset_path: ${data.data_dir} # Path to the dataset
  alpha_u: ${model.alpha_u}
  vel_solver: ${model.vel_solver}
  v2u_solver: ${model.v2u_solver}
  isotropic_norm: false
  node_features_type: ["v"] # ["v", "u", "type"]
  # kwargs
  mlp_num_layers: 1
  mlp_hidden_dim: 128

# Optimizer configuration
optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 1e-4 # 1e-4 performs almost same as 3e-4. 3e-4 might be a problem to overfit
  weight_decay: 1.e-8

# # Scheduler configuration
# scheduler:
#   _partial_: true
#   _target_: src.utils.schedulers.LinearWarmupCosineAnnealingLR
#   optimizer: ${..optimizer} # Reference optimizer from the model configuration
#   min_lr: 0.0001
#   steps_per_epoch: 1
#   warmup_epochs: 0
#   max_epochs: 10

# scheduler:
#   _target_: src.utils.schedulers.ExpDecayLR
#   _partial_: true
#   init_value: ${..optimizer.lr}
#   transition_steps: 250_000
#   decay_rate: 0.1
#   end_value: 1.0e-6

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 200_000
  gamma: 0.5

# Set whether to compile the model
compile: true

# Adjust based on the available hardware
accelerator: ${trainer.accelerator}

#By default, pushforward is disabled
pushforward:
  steps: [-1]
  unrolls: [0]
  probs: [1]

neuralsph:
  val:
    is_tvf: False
    dt_factor: 1
    num_steps: 0
  test:
    is_tvf: False
    dt_factor: 1
    num_steps: 0

num_rollout_steps: ${vars.num_rollout_steps}
active_metrics: ["mse", "e_kin", "mse_pos"]
metric_space:
  val: "norm" # {"phys", "norm", "diff"} = physical, normalized, difference
  test: "phys"
  interpolate:
    condition: radius # "radius", "knn"  # TODO: compare runtime against knn with k=3
    k: 15
    cutoff_factor: 2.0 # for Quintic would have been 3, but here it is just a metric
    kernel: "quintic" # "quintic", "xsqinv"

alpha_u: 0.0
alpha_v: 1.0

visualize:
  vis_test:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: "${paths.log_dir}/${task_name}/runs/WANDB_ID/rlt/test" #interpolation of the ID is done in the main script
    animate_first_n: 1
  vis_val:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: null
    animate_first_n: 0
