
# configs/model/gns.yaml

# Specify the correct path to the SimulatorLitModule in the Lightning module
_target_: src.models.gnn_module.GNNLitModule # Adjust this to the actual path for your GNS Lightning module

net:
  # Specify the correct path to the GNS model implementation (GNNSimulator) within the SimulatorLitModule
  _target_: src.models.gnn_module.GNNSimulator # Adjust this to the actual path for your GNS simulator model
  _partial_: true
  model_name: "lles"
  input_seq_length: ${vars.input_seq_length}
  dataset_path: ${data.data_dir} # Path to the dataset
  noise_std: 3.0e-4

  # GNS specific parameters, not needed for LLES
  latent_dim: null
  num_message_passing_steps: null
  num_particle_types: null # Set to None for no particle type embedding
  particle_type_embedding_size: null

  alpha_u: ${model.alpha_u}
  vel_solver: ${model.vel_solver}
  isotropic_norm: false
  # kwargs
  input_features: 3
  hidden_dims: [20, 100, 20]
  output_dim: 4
  activation: "tanh" # tanh, relu, sigmoid

#Loss coefficients
alpha_u: 1.0
alpha_v: 1.0
alpha_field: 1.0

#Optimizer configuration
optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 3e-7
  weight_decay: 1.e-8

#Scheduler configuration
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 100_000
  gamma: 0.5

# Set whether to compile the model
compile: true

# Adjust based on the available hardware
accelerator: ${trainer.accelerator}

#By default, pushforward is disabled
pushforward:
  steps: [-1]
  unrolls: [0]
  probs: [1]

neuralsph:
  val:
    is_tvf: False
    dt_factor: 1
    num_steps: 0
  test:
    is_tvf: False
    dt_factor: 1
    num_steps: 0

num_rollout_steps: ${vars.num_rollout_steps}
active_metrics: ["mse", "e_kin", "mse_pos"]
metric_space:
  val: "norm" # {"phys", "norm", "diff"} = physical, normalized, difference
  test: "phys"
  interpolate: 
    condition: "radius" # "radius", "knn"
    k: 15 # number of neighbors for knn
    cutoff_factor: 3.0 # for radius
    kernel: "xsqinv" # "quintic", "xsqinv"
    # grid_res: 32 # grid resolution for interpolation

#Visualization settings
visualize:
  vis_test:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: "${paths.log_dir}/train/runs/WANDB_ID/rlt/test" #interpolation of the ID is done in the main script
  vis_val:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: null
