# configs/model/gns.yaml

# Specify the correct path to the SimulatorLitModule in the Lightning module
_target_: src.models.simulator_module.SimulatorLitModule  # Adjust this to the actual path for your GNS Lightning module

net:
  # Specify the correct path to the GNS model implementation (Simulator) within the SimulatorLitModule
  _target_: src.models.simulator.Simulator  # Adjust this to the actual path for your GNS simulator model
  _partial_: true
  model_name: "segnn"
  input_seq_length: ${vars.input_seq_length}
  latent_dim: 64
  num_message_passing_steps: 10
  noise_std: 3.0e-4 
  num_particle_types: 9
  particle_type_embedding_size: 16
  dataset_path: ${data.data_dir} # Path to the dataset
  alpha_u: ${model.alpha_u}
  vel_solver: ${model.vel_solver}
  # kwargs
  lmax_attr: 1
  lmax_hidden: 1
  velocity_aggregate: "avg"
  norm: "none"

# Optimizer configuration
optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${..scheduler.init_value}
  weight_decay: 1.e-8

scheduler:
  _target_: src.utils.schedulers.ExpDecayLR
  _partial_: true
  init_value: 1.0e-4
  transition_steps: 100_000
  decay_rate: 0.1
  end_value: 1.0e-6

# Set whether to compile the model
compile: true

# Adjust based on the available hardware
accelerator: ${trainer.accelerator}

#By default, pushforward is disabled
pushforward:
  steps: [-1]
  unrolls: [0]
  probs: [1]

neuralsph:
  val:
    is_tvf: False
    dt_factor: 1
    num_steps: 0
  test:
    is_tvf: False
    dt_factor: 1
    num_steps: 0

num_rollout_steps: ${vars.num_rollout_steps}
active_metrics: ["mse", "e_kin"]
alpha_u: 0.0
alpha_v: 1.0

visualize:
  vis_test:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: "${paths.log_dir}/rollouts/wandb_id/test" #interpolation of the ID is done in the main script
  vis_val:
    out_type: "none" # "none", "vtk", "pkl"
    rollout_dir: null
