# Default callbacks configuration
defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "{epoch:02d}-{step:06d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  # auto_insert_metric_name: False
  every_n_train_steps: ${trainer.val_check_interval}

early_stopping:
  monitor: "val/loss"
  patience: 20 # we evaluate every 10k steps, so this is 200k steps
  mode: "min"

model_summary:
  max_depth: -1
# lr_scheduler_callback:
#     _target_: src.callbacks.config_lr_scheduler.ConfigLRScheduler
