# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - callbacks: default
  - trainer: default
  - paths: default
  - extras: default
  - vars: default
  - experiment: null
  - hydra: default

task_name: "eval"

tags: ["dev"]

ckpt_path: path/to/checkpoint.ckpt
