# @package _global_

# overfit one 1 short trajectory sample

defaults:
  - default

# callbacks and loggers during debugging
callbacks:
  early_stopping:
    patience: 10000000
logger:
  wandb:
    name: ${task_name}

trainer:
  log_every_n_steps: 1
  limit_train_batches: ${vars.num_rollout_steps}
  limit_val_batches: 1
  limit_test_batches: 1
  val_check_interval: 10
  max_epochs: -1
  max_steps: 200 # Train iters

data:
  shuffle: True
  limit_train_batches: ${vars.num_rollout_steps}
  overfit: True

vars:
  num_rollout_steps: 1 # STEPS

# IF GNS
model:
  net:
    noise_std: 0.0
  visualize:
    vis_test:
      out_type: vtk
