config: src/validate_code/tgv_lagrbench/gns.yaml
load_ckp: null
mode: all
seed: 0
dtype: float64
gpu: -1
xla_mem_fraction: 0.75
dataset:
  src: /home/tkalinov/code/sph_les_directory/sph_les/data/2D_TGV_2500_10kevery100
  name: null
model:
  name: gns
  input_seq_length: 6
  num_mp_steps: 2
  num_mlp_layers: 1
  latent_dim: 128
  magnitude_features: false
  isotropic_norm: false
  lmax_attributes: 1
  lmax_hidden: 1
  segnn_norm: none
  velocity_aggregate: avg
  latent_size: 9
  particle_type_embedding_size: 16
train:
  batch_size: 1
  step_max: 500000
  num_workers: 0
  noise_std: 0
  optimizer:
    lr_start: 0.0001
    lr_final: 1.0e-06
    lr_decay_rate: 0.1
    lr_decay_steps: 100000.0
  pushforward:
    steps:
    - -1
    unrolls:
    - 0
    probs:
    - 1
  loss_weight:
    acc: 1.0
    vel: 0.0
    pos: 0.0
eval:
  n_rollout_steps: 20
  test: false
  rollout_dir: null
  train:
    n_trajs: 50
    metrics_stride: 10
    batch_size: 1
    metrics:
    - mse
    out_type: none
  infer:
    n_trajs: -1
    metrics_stride: 1
    batch_size: 2
    metrics:
    - mse
    - e_kin
    out_type: pkl
    n_extrap_steps: 0
logging:
  log_steps: 1000
  eval_steps: 10000
  wandb: true
  wandb_project: tgv2d
  wandb_entity: lagrangebench
  ckp_dir: ckp
  run_name: gns_tgv2d_LB
neighbors:
  backend: jaxmd_vmap
  multiplier: 1.25
