# Run pre-commit on push or PR to main branch

name: Code Quality Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run pre-commits
        uses: pre-commit/action@v3.0.1
